include:
  - project: graphaware/devops/gitlab-ci-templates
    file: neo4j-framework-template.yml

variables:
  JAR_NAME: timetree

publishJavaDoc:
  extends: .publishJavaDoc
  variables:
    FROM: target/apidocs
    TO: timetree